CREATE TABLE IF NOT EXISTS CREDIT_PAYMENT_ALLOCATIONS (
    ID VARCHAR(64) NOT NULL PRIMARY KEY,
    PAYMENT_ID VARCHAR(32) NOT NULL,
    PAYMENT_FOLIO VARCHAR(32) NOT NULL,
    CUSTOMER_ID VARCHAR(32) NOT NULL,
    SALE_KEY VARCHAR(80) NOT NULL,
    TICKET_ID VARCHAR(32) NOT NULL DEFAULT '',
    SALE_FOLIO VARCHAR(32) NOT NULL,
    MONTO DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    CUANDO_FUE DATETIME NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_CPA_PAYMENT_ID (PAYMENT_ID),
    INDEX IDX_CPA_CUSTOMER_ID (CUSTOMER_ID),
    INDEX IDX_CPA_SALE_KEY (SALE_KEY),
    INDEX IDX_CPA_TICKET_ID (TICKET_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
