CREATE TABLE IF NOT EXISTS FACT_ELEC_DOCUMENTOS_ARCHIVOS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    DOCUMENT_ID VARCHAR(32) NOT NULL,
    FILE_KIND VARCHAR(32) NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    MIME_TYPE VARCHAR(120) NOT NULL,
    FILE_SIZE BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONTENT LONGBLOB NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY UQ_FACT_ELEC_FILE_DOC_KIND (DOCUMENT_ID, FILE_KIND),
    KEY IDX_FACT_ELEC_FILE_DOC (DOCUMENT_ID),
    CONSTRAINT FK_FACT_ELEC_FILE_DOC
        FOREIGN KEY (DOCUMENT_ID) REFERENCES FACT_ELEC_DOCUMENTOS(ID)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
